# backend/viz_engine.py

import os

from dotenv import load_dotenv
from pydantic import BaseModel, Field
from langchain_google_genai import ChatGoogleGenerativeAI


# Load environment variables safely.
load_dotenv()
  

# ============================================================
# STRUCTURED SCHEMA DEFINITIONS
# ============================================================

class ControlSlider(BaseModel):
    id: str = Field(
        description=(
            "Unique camelCase identifier used inside metric_script and "
            "canvas_script. Example: velocity, angle, gravity, temperature."
        )
    )

    label: str = Field(
        description=(
            "Human-readable label displayed beside the slider. "
            "Example: Initial Velocity."
        )
    )

    min: float = Field(
        description="Minimum numeric value allowed by the slider."
    )

    max: float = Field(
        description="Maximum numeric value allowed by the slider."
    )

    default: float = Field(
        description="Initial/default numeric value of the slider."
    )

    unit: str = Field(
        description=(
            "Short unit displayed with the value. "
            "Examples: m/s, m, s, K, Hz, °. Use an empty string if unitless."
        )
    )


class MatrixColumn(BaseModel):
    id: str = Field(
        description=(
            "Column identifier. Use one of: parameter, value, range, unit."
        )
    )

    label: str = Field(
        description="Human-readable column heading."
    )


class MatrixConfig(BaseModel):
    title: str = Field(
        default="PARAMETER MATRIX",
        description="Title displayed above the parameter matrix."
    )

    columns: list[MatrixColumn] = Field(
        description=(
            "Columns used by the parameter matrix. "
            "Normally use parameter, value, range and unit."
        )
    )


class MetricCard(BaseModel):
    id: str = Field(
        description=(
            "Unique camelCase identifier used by metric_script. "
            "Example: range, discriminant, vertex, reactionRate."
        )
    )

    label: str = Field(
        description=(
            "Human-readable uppercase display label for the metric."
        )
    )

    unit: str = Field(
        description=(
            "Unit displayed beside the calculated metric. "
            "Use an empty string if the metric has no unit."
        )
    )


class VizConfigSchema(BaseModel):
    concept_name: str = Field(
        description=(
            "Clean uppercase title describing the academic STEM concept."
        )
    )

    sliders: list[ControlSlider] = Field(
        description=(
            "Interactive controls for the visualization. "
            "Use 1-6 sliders when useful. Do not create unnecessary sliders."
        )
    )

    matrix: MatrixConfig = Field(
        description=(
            "Configuration for the parameter matrix shown below the sliders. "
            "The matrix values are automatically generated by the frontend."
        )
    )

    metrics: list[MetricCard] = Field(
        description=(
            "Calculated analytical values displayed below the matrix. "
            "Use 1-5 metrics when useful."
        )
    )

    metric_script: str = Field(
        description=(
            "Pure JavaScript code that calculates metrics. "
            "It receives ctx, sliders, metrics and runtime. "
            "Store calculated values inside metrics using metrics.metricId = value. "
            "Do not access the DOM. Do not use document.getElementById. "
            "Do not draw anything in this script."
        )
    )

    canvas_script: str = Field(
        description=(
            "Pure JavaScript code that draws the visualization. "
            "It receives ctx, sliders, metrics and runtime. "
            "It runs repeatedly inside requestAnimationFrame. "
            "Do not use document APIs. Do not use window variables. "
            "Use runtime for persistent animation state."
        )
    )


# ============================================================
# GENERATOR ENGINE
# ============================================================

async def generate_visualization_data(subject: str, concept: str) -> dict:
    api_key = os.getenv("GEMINI_API_KEY_1")

    if not api_key:
        raise ValueError(
            "Missing GEMINI_API_KEY_1 value inside server configuration."
        )

    # Initialize Gemini.
    llm = ChatGoogleGenerativeAI(
        model="gemini-3.5-flash",
        google_api_key=api_key,
        timeout=60,
        max_retries=1,
    )

    # Enable structured output.
    structured_llm = llm.with_structured_output(VizConfigSchema)

    # ========================================================
    # SYSTEM INSTRUCTION
    # ========================================================

    system_instruction = """
You are an expert STEM interactive visualization engine.

Your job is to analyze an academic concept and generate a complete
visualization configuration for a Next.js HTML5 Canvas application.

The visualization has FOUR runtime objects available to JavaScript:

1. ctx
   HTML5 CanvasRenderingContext2D.

2. sliders
   Live object containing current slider values.
   Example:
   sliders.velocity
   sliders.angle

3. metrics
   Mutable object used to store calculated metric values.
   Example:
   metrics.range = 42.5
   metrics.vertex = "(2.00, -3.00)"

4. runtime
   Persistent object that survives animation frames.
   Use this for animation state, particles, timers, histories,
   counters and other persistent visualization data.

IMPORTANT:
Never use window for application state.

Do NOT create:
window.simTime
window.waveTime
window.kineticsParticles

Instead use:
runtime.simTime
runtime.waveTime
runtime.kineticsParticles

============================================================
SLIDERS
============================================================

Create only useful sliders.

Each slider must contain:

id
label
min
max
default
unit

Slider IDs must be unique camelCase identifiers.

============================================================
MATRIX
============================================================

Always provide a matrix configuration.

The normal matrix columns are:

parameter
value
range
unit

Example:

{
  "title": "PARAMETER MATRIX",
  "columns": [
    {"id": "parameter", "label": "Parameter"},
    {"id": "value", "label": "Current Value"},
    {"id": "range", "label": "Range"},
    {"id": "unit", "label": "Unit"}
  ]
}

Do NOT put changing slider values inside the matrix.
The frontend calculates those automatically.

============================================================
METRICS
============================================================

Metrics describe calculated values shown below the visualization.

Each metric contains:

id
label
unit

For example:

discriminant
vertex
roots

or:

reactionRate
completion

============================================================
METRIC SCRIPT
============================================================

metric_script is responsible ONLY for calculations.

It receives:

ctx
sliders
metrics
runtime

Store calculated values using:

metrics.metricId = value;

Examples:

metrics.range = calculatedRange;

metrics.vertex = `(${h.toFixed(2)}, ${k.toFixed(2)})`;

metrics.state = "CONSTRUCTIVE";

Do NOT use:

document.getElementById()
document.querySelector()
innerText
textContent

Do NOT manipulate HTML.

Do NOT draw anything on the canvas.

The frontend automatically displays the metric values.

The metric script can use runtime when a calculation needs
persistent animation/history data.

============================================================
CANVAS SCRIPT
============================================================

canvas_script is responsible ONLY for drawing the visualization.

It receives:

ctx
sliders
metrics
runtime

The parent framework clears the canvas before every frame.

Therefore DO NOT call:

ctx.clearRect()

The canvas coordinate system is:

width = 500
height = 320

Keep the actual drawing coordinates within this logical
500 x 320 coordinate system.

The frontend automatically scales this canvas to fit the available
screen width while preserving the aspect ratio.

============================================================
ANIMATION
============================================================

For animation use runtime.

Example:

if (runtime.time === undefined) {
  runtime.time = 0;
}

runtime.time += 0.03;

Never use window variables.

Persistent arrays should also be stored in runtime:

if (!runtime.particles) {
  runtime.particles = [];
}

============================================================
LIGHT THEME
============================================================

The entire visualization must use a LIGHT theme.

Do NOT use dark backgrounds.

Canvas background should normally be:

#ffffff

Recommended colors:

Grid:
#e2e8f0

Axis:
#64748b

Primary:
#3b82f6

Secondary:
#ec4899

Success:
#10b981

Warning:
#eab308

Danger:
#ef4444

Text:
#334155

Secondary text:
#64748b

Do NOT use:

#0f172a as a canvas background
rgba(15,23,42,...)
#f8fafc as primary text on a dark background

============================================================
CANVAS SCRIPT RESTRICTIONS
============================================================

The canvas script must:

- contain only valid JavaScript
- contain no Markdown
- contain no ```javascript fences
- work whether formatted with newlines or minified into one line
- not use document APIs
- not use window application state
- not depend on HTML element IDs
- not update HTML
- use ctx for visualization
- use sliders for live controls
- use metrics for calculated values
- use runtime for persistent state

Do not assume a specific number of sliders or metrics.

============================================================
EXAMPLE: QUADRATIC EQUATION
============================================================

Possible sliders:

coeffA
coeffB
coeffC

Possible metrics:

discriminant
vertex
roots

metric_script should calculate these values and put them into:

metrics.discriminant
metrics.vertex
metrics.roots

canvas_script should only draw the graph and use:

sliders.coeffA
sliders.coeffB
sliders.coeffC

============================================================
EXAMPLE: WAVE INTERFERENCE
============================================================

Possible sliders:

freq1
freq2
phase

Possible metrics:

beat
state

metric_script should calculate:

metrics.beat
metrics.state

canvas_script should draw the waves.

Animation state should use:

runtime.waveTime

NOT:

window.waveTime

============================================================
EXAMPLE: CHEMICAL KINETICS
============================================================

Particles and collision history should use:

runtime.particles
runtime.successfulCollisions
runtime.totalCollisions
runtime.collisionHistory

Metrics should be calculated inside metric_script.

Do NOT use:

document.getElementById()

The React application automatically displays metric values.

============================================================
QUALITY
============================================================

The visualization must be educational, visually clear,
interactive and mathematically/scientifically meaningful.

Prefer a useful visualization over decorative elements.

Return ONLY the structured schema requested by the application.
"""

    user_prompt = f"""
Subject Category:
{subject}

Target Technical Concept:
{concept}

Generate the complete interactive visualization configuration.
"""

    # ========================================================
    # GENERATE STRUCTURED RESPONSE
    # ========================================================

    response_model = await structured_llm.ainvoke(
        [
            ("system", system_instruction),
            ("user", user_prompt),
        ]
    )

    # ========================================================
    # RETURN DICTIONARY
    # ========================================================

    if isinstance(response_model, BaseModel):
        return response_model.model_dump()

    if isinstance(response_model, dict):
        return response_model

    raise TypeError(
        f"Gemini returned an unsupported response type: "
        f"{type(response_model).__name__}"
    )

